//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyList.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyList.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmfile.
        /// </summary>
        public static string appBMName {
            get {
                return ResourceManager.GetString("appBMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBNotes.
        /// </summary>
        public static string appDBName {
            get {
                return ResourceManager.GetString("appDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableOfNotes.
        /// </summary>
        public static string appDBTableName {
            get {
                return ResourceManager.GetString("appDBTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivedNotes.
        /// </summary>
        public static string appGotJsonFile {
            get {
                return ResourceManager.GetString("appGotJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangesNotes.
        /// </summary>
        public static string appJsonFile {
            get {
                return ResourceManager.GetString("appJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string appMusFolderName {
            get {
                return ResourceManager.GetString("appMusFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyList.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\\MyList.
        /// </summary>
        public static string appRegPath {
            get {
                return ResourceManager.GetString("appRegPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkResources.
        /// </summary>
        public static string appResFolderName {
            get {
                return ResourceManager.GetString("appResFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string appStopName {
            get {
                return ResourceManager.GetString("appStopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bookmark {
            get {
                object obj = ResourceManager.GetObject("bookmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Cross {
            get {
                object obj = ResourceManager.GetObject("Cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lightCheck {
            get {
                object obj = ResourceManager.GetObject("lightCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap musorka {
            get {
                object obj = ResourceManager.GetObject("musorka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon note {
            get {
                object obj = ResourceManager.GetObject("note", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap notepad {
            get {
                object obj = ResourceManager.GetObject("notepad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap param {
            get {
                object obj = ResourceManager.GetObject("param", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsFirstDelete.
        /// </summary>
        public static string regIsFirstDelete {
            get {
                return ResourceManager.GetString("regIsFirstDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsFirstMain.
        /// </summary>
        public static string regIsFirstMain {
            get {
                return ResourceManager.GetString("regIsFirstMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsFirstRemindExit.
        /// </summary>
        public static string regIsFirstRemindExit {
            get {
                return ResourceManager.GetString("regIsFirstRemindExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsFocusText.
        /// </summary>
        public static string regIsFocusText {
            get {
                return ResourceManager.GetString("regIsFocusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSound.
        /// </summary>
        public static string regIsSound {
            get {
                return ResourceManager.GetString("regIsSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string regLanguage {
            get {
                return ResourceManager.GetString("regLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicFile.
        /// </summary>
        public static string regMusicFile {
            get {
                return ResourceManager.GetString("regMusicFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PastHeight.
        /// </summary>
        public static string regPastHeight {
            get {
                return ResourceManager.GetString("regPastHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PastWidth.
        /// </summary>
        public static string regPastWidth {
            get {
                return ResourceManager.GetString("regPastWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Revoke {
            get {
                object obj = ResourceManager.GetObject("Revoke", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
